version: '3'

services:
  alg:
    image: alg
    ports:
      - "4000:4000"
    volumes:
      - ./rotund.institute/data.json:/srv/algernon/rotund.institute/data.json
      - ./rotund.institute/files:/srv/algernon/rotund.institute/files
    stdin_open: true
    tty: true
